[[project]]
    name = "pyba"
    desc = "This is a browser automation framework for OSINT. Its got a bunch of cool plugins like memory and token optimisations and runs pretty darn fast."
    tags = ["python", "automation", "browsers"]
    links = [
        { name = "GitHub", url = "https://github.com/fauvidoTechnologies/PyBrowserAutomation/"},
        { name = "PyPi", url = "https://pypi.org/project/py-browser-automation/"},
        { name = "Examples", url = "https://github.com/FauvidoTechnologies/PyBrowserAutomation/tree/main/automation_eval"}
    ]

[[project]]
    name = "homelab"
    desc = "I am building a homelab. This is to learn about computer networking and experiment with hardware and different services. This is an ongoing project and more on this is available in the blog section!"
    tags = ["Networking", "Homelab", "Cybersec"]
    links = [
      { name = "nothing", url = "https://youtu.be/dQw4w9WgXcQ" }
    ]